fix violation of gcc warning -Wshadow
Summary:
Addresses this compile error:

```
fatal/test/test.h: In instantiation of ‘fatal::test::detail::test_impl::check_wrapper<Category, Predicate, ArgsTuple>::check_wrapper(UPredicate&&, fatal::source_info, UArgsTuple&&) [with UPredicate = fatal::test::detail::test_impl::predicates::is_equal; UArgsTuple = std::tuple<const char*, const char*>; Category = fatal::test::detail::test_impl::categories::expectation; Predicate = fatal::test::detail::test_impl::predicates::is_equal; ArgsTuple = std::tuple<const char*, const char*>]’:
fatal/test/test.h:687:3:   required from ‘fatal::test::detail::test_impl::check_wrapper<Category, typename std::decay<_Tp2>::type, typename std::decay<ArgsTuple>::type> fatal::test::detail::test_impl::make_check_wrapper(Predicate&&, fatal::source_info, ArgsTuple&&) [with Category = fatal::test::detail::test_impl::categories::expectation; Predicate = fatal::test::detail::test_impl::predicates::is_equal; ArgsTuple = std::tuple<const char*, const char*>; typename std::decay<ArgsTuple>::type = std::decay<std::tuple<const char*, const char*> >::type; typename std::decay<_Tp2>::type = std::decay<fatal::test::detail::test_impl::predicates::is_equal>::type]’
fatal/type/test/map_test.cpp:1012:3:   required from here
fatal/test/test.h:571:18: error: declaration of ‘predicate’ shadows a member of ‘fatal::test::detail::test_impl::check_wrapper<fatal::test::detail::test_impl::categories::expectation, fatal::test::detail::test_impl::predicates::is_equal, std::tuple<const char*, const char*> >’ [-Werror=shadow]
  571 |     UPredicate &&predicate,
      |     ~~~~~~~~~~~~~^~~~~~~~~
fatal/test/test.h:564:9: note: shadowed declaration is here
  564 |   using predicate = Predicate;
      |         ^~~~~~~~~
```

Differential Revision: D37423101

fbshipit-source-id: c23232619a6ec3d1c7242b07bd1d3ef965f9ce49