fix a cxx20 issue in rope
Summary:
Fixes the following compile error:

```
fatal/string/rope.h: In instantiation of ‘bool fatal::operator==(const T&, const fatal::rope<SmallBufferSize>&) [with T = char*; long unsigned int SmallBufferSize = 8; <template-parameter-1-3> = void]’:
fatal/string/test/rope_test.cpp:270:3:   required from here
fatal/string/rope.h:1728:14: error: in C++20 this comparison calls the current function recursively with reversed arguments [-Werror]
 1728 |   return rhs == lhs;
      |          ~~~~^~~~~~
```

Differential Revision: D37425279

fbshipit-source-id: d3086d50e6cd48481d7a1b16f9c45b6d7955f3fc